/**
 * Identity Domain Schema
 *
 * Core tables are managed by Better Auth (users, sessions, accounts, verifications).
 * We extend with a profile table to keep auth concerns separate from user data.
 *
 * NOTE: The users, sessions, accounts, and verifications tables are
 * auto-generated by `npx auth generate`. We define them here explicitly
 * so Drizzle kit can manage migrations for the full schema in one place.
 */
import {
	pgTable,
	text,
	timestamp,
	boolean,
	integer,
	uuid
} from 'drizzle-orm/pg-core';

/** Better Auth — core users table */
export const users = pgTable('users', {
	id:            text('id').primaryKey(),
	name:          text('name').notNull().default(''),
	email:         text('email').notNull().unique(),
	emailVerified: boolean('email_verified').notNull().default(false),
	image:         text('image'),
	createdAt:     timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
	updatedAt:     timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
	role:          text('role').notNull().default('student'),
	banned:        boolean('banned').notNull().default(false),
	banReason:     text('ban_reason'),
	banExpires:    timestamp('ban_expires', { withTimezone: true }),
	mustChangePassword: boolean('must_change_password').notNull().default(false)
});

/** Better Auth — sessions */
export const sessions = pgTable('sessions', {
	id:             text('id').primaryKey(),
	expiresAt:      timestamp('expires_at', { withTimezone: true }).notNull(),
	token:          text('token').notNull().unique(),
	createdAt:      timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
	updatedAt:      timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
	ipAddress:      text('ip_address'),
	userAgent:      text('user_agent'),
	userId:         text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' })
});

/** Better Auth — OAuth + OTP account links */
export const accounts = pgTable('accounts', {
	id:                   text('id').primaryKey(),
	accountId:            text('account_id').notNull(),
	providerId:           text('provider_id').notNull(),
	userId:               text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
	accessToken:          text('access_token'),
	refreshToken:         text('refresh_token'),
	idToken:              text('id_token'),
	accessTokenExpiresAt: timestamp('access_token_expires_at', { withTimezone: true }),
	refreshTokenExpiresAt: timestamp('refresh_token_expires_at', { withTimezone: true }),
	scope:                text('scope'),
	password:             text('password'),
	createdAt:            timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
	updatedAt:            timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
});

/** Better Auth — OTP verification records */
export const verifications = pgTable('verifications', {
	id:         text('id').primaryKey(),
	identifier: text('identifier').notNull(),
	value:      text('value').notNull(),
	expiresAt:  timestamp('expires_at', { withTimezone: true }).notNull(),
	createdAt:  timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
	updatedAt:  timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
});

/**
 * User profiles — extended identity data.
 * Separated from Better Auth's users table to maintain clear boundaries.
 * Profile is created automatically on first sign-in via the auth hook.
 */
export const identityProfiles = pgTable('identity_profiles', {
	id:          text('id').primaryKey(),
	userId:      text('user_id').notNull().unique().references(() => users.id, { onDelete: 'cascade' }),
	displayName: text('display_name'),
	bio:         text('bio'),
	avatarUrl:   text('avatar_url'),
	timezone:    text('timezone').notNull().default('Asia/Kolkata'),
	loginPreference: text('login_preference', { enum: ['otp', 'password'] }).notNull().default('otp'),
	createdAt:   timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
	updatedAt:   timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
});

export const auditLogs = pgTable('audit_logs', {
	id:        text('id').primaryKey(),
	actorId:   text('actor_id').notNull().references(() => users.id), // Who did it
	action:    text('action').notNull(), // e.g., 'role_change', 'transfer_ownership', 'ban_user'
	entityId:  text('entity_id'), // The ID of the thing they acted upon
	entityType:text('entity_type'), // e.g., 'user', 'course'
	details:   text('details'), // JSON string or text describing the change
	createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow()
});

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Session = typeof sessions.$inferSelect;
export type IdentityProfile = typeof identityProfiles.$inferSelect;
export type NewIdentityProfile = typeof identityProfiles.$inferInsert;
export type AuditLog = typeof auditLogs.$inferSelect;
export type NewAuditLog = typeof auditLogs.$inferInsert;
